// src/components/modules/Kondukter.tsx
'use client';

import { useState } from 'react';
import { motion } from 'framer-motion';

/* ─── Button definitions ─── */
const buttons = [
  // Row 1
  { id: 'zasoby', primary: 'ZÁSOBY', secondary: 'ЗАЛИХЕ', danger: false },
  { id: 'mapa', primary: 'MAPA', secondary: 'КАРТА', danger: false },
  { id: 'plato', primary: 'PLATO', secondary: 'ПЛАТО', danger: false },
  { id: 'zahrada', primary: 'ZÁHRADA', secondary: 'БАШТА', danger: false },
  // Row 2
  { id: 'sprievodca', primary: 'SPRIEVODCA', secondary: 'ВОДИЧ', danger: false },
  { id: 'clenovia', primary: 'ČLENOVIA', secondary: 'ЧЛАНОВИ', danger: false },
  { id: 'navrhy', primary: 'NÁVRHY', secondary: 'ПРЕДЛОЗИ', danger: false },
  { id: 'poplach', primary: 'POPLACH', secondary: 'УЗБУНА', danger: true },
];

const toggleSwitches = [
  { id: 'zvuk', primary: 'ZVUK', secondary: 'ЗВУК' },
  { id: 'crt', primary: 'CRT', secondary: 'ЕКРАН' },
  { id: 'alarm', primary: 'ALARM', secondary: 'АЛАРМ' },
  { id: 'offline', primary: 'OFFLINE', secondary: 'ОФЛАЈН' },
];

/* ─── LED colors by index ─── */
const ledColors = ['#33CC33', '#E6A817', '#33CC33', '#E6A817', '#33CC33', '#E6A817', '#33CC33', '#CD2500'];

/* ─── Sub-components ─── */

function PhysicalButton({
  btn,
  index,
  active,
  onPress,
}: {
  btn: (typeof buttons)[0];
  index: number;
  active: boolean;
  onPress: () => void;
}) {
  const ledColor = btn.danger ? '#CD2500' : ledColors[index];

  return (
    <div className="flex flex-col items-center" style={{ gap: '4px' }}>
      <motion.button
        onClick={onPress}
        whileTap={{ y: 2 }}
        animate={{ y: active ? 1 : 0 }}
        transition={{ type: 'spring', stiffness: 600, damping: 30 }}
        style={{
          width: '90px',
          height: '52px',
          background: btn.danger
            ? 'linear-gradient(180deg, #e8e0d0 0%, #ddd4c4 40%, #d0c8b8 100%)'
            : 'linear-gradient(180deg, #f0ebe0 0%, #e8e0d0 40%, #ddd4c4 100%)',
          border: '1px solid #b0a890',
          borderRadius: '4px',
          boxShadow: active
            ? 'inset 0 1px 2px rgba(0,0,0,0.15), 0 1px 0 rgba(255,255,255,0.3)'
            : '0 2px 4px rgba(0,0,0,0.25), 0 1px 0 rgba(255,255,255,0.3), inset 0 1px 0 rgba(255,255,255,0.5)',
          cursor: 'pointer',
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
          justifyContent: 'center',
          gap: '1px',
          padding: '4px 2px',
          fontFamily: 'var(--font-mono)',
          position: 'relative',
        }}
      >
        {/* Danger indicator dot on POPLACH */}
        {btn.danger && (
          <span
            style={{
              position: 'absolute',
              top: '4px',
              left: '6px',
              width: '5px',
              height: '5px',
              borderRadius: '50%',
              background: '#CD2500',
              boxShadow: active ? '0 0 6px #CD2500' : 'none',
            }}
          />
        )}
        <span
          style={{
            fontSize: '10px',
            fontWeight: 700,
            color: btn.danger ? '#B22222' : '#2a2a2a',
            lineHeight: 1.1,
            letterSpacing: '0.02em',
          }}
        >
          {btn.primary}
        </span>
        <span
          style={{
            fontSize: '9px',
            fontWeight: 500,
            color: btn.danger ? '#8B1A1A' : '#666',
            lineHeight: 1.1,
          }}
        >
          {btn.secondary}
        </span>
      </motion.button>

      {/* LED indicator below button */}
      <div
        style={{
          width: '6px',
          height: '6px',
          borderRadius: '50%',
          background: active ? ledColor : '#4a4a3a',
          boxShadow: active ? `0 0 6px ${ledColor}, 0 0 12px ${ledColor}40` : 'inset 0 1px 1px rgba(0,0,0,0.3)',
          transition: 'all 0.15s ease',
        }}
      />
    </div>
  );
}

function ToggleSwitch({
  toggle,
  active,
  onToggle,
}: {
  toggle: (typeof toggleSwitches)[0];
  active: boolean;
  onToggle: () => void;
}) {
  return (
    <div className="flex flex-col items-center" style={{ gap: '3px' }}>
      {/* Top labels */}
      <div className="flex flex-col items-center" style={{ gap: '0px' }}>
        <span
          style={{
            fontSize: '9px',
            fontWeight: 700,
            color: '#2a2a2a',
            fontFamily: 'var(--font-mono)',
            letterSpacing: '0.05em',
          }}
        >
          {toggle.primary}
        </span>
        <span
          style={{
            fontSize: '8px',
            fontWeight: 500,
            color: '#666',
            fontFamily: 'var(--font-mono)',
          }}
        >
          {toggle.secondary}
        </span>
      </div>

      {/* Toggle housing */}
      <button
        onClick={onToggle}
        style={{
          width: '28px',
          height: '48px',
          background: 'linear-gradient(180deg, #3a3a34 0%, #2a2a24 50%, #3a3a34 100%)',
          borderRadius: '4px',
          border: '1px solid #222',
          boxShadow: 'inset 0 2px 4px rgba(0,0,0,0.4), 0 1px 0 rgba(255,255,255,0.05)',
          position: 'relative',
          cursor: 'pointer',
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
          justifyContent: active ? 'flex-start' : 'flex-end',
          padding: '3px',
        }}
      >
        {/* Toggle lever */}
        <motion.div
          animate={{ y: active ? 0 : 0 }}
          layout
          transition={{ type: 'spring', stiffness: 500, damping: 30 }}
          style={{
            width: '20px',
            height: '20px',
            borderRadius: '3px',
            background: active
              ? 'linear-gradient(180deg, #e8e0d0 0%, #ccc4b0 100%)'
              : 'linear-gradient(180deg, #888070 0%, #706860 100%)',
            boxShadow: active
              ? '0 2px 4px rgba(0,0,0,0.3), inset 0 1px 0 rgba(255,255,255,0.4)'
              : '0 -2px 4px rgba(0,0,0,0.3), inset 0 -1px 0 rgba(255,255,255,0.1)',
            border: '1px solid rgba(0,0,0,0.2)',
          }}
        />
      </button>

      {/* Bottom labels */}
      <div className="flex flex-col items-center" style={{ gap: '0px', marginTop: '-1px' }}>
        <span
          style={{
            fontSize: '7px',
            fontWeight: 600,
            color: active ? '#33CC33' : '#888',
            fontFamily: 'var(--font-mono)',
            letterSpacing: '0.08em',
            transition: 'color 0.15s',
          }}
        >
          {active ? 'ON' : 'OFF'}
        </span>
      </div>
    </div>
  );
}

/* ─── Main Kondukter Module ─── */

export default function Kondukter() {
  const [activeButtons, setActiveButtons] = useState<Record<string, boolean>>({});
  const [toggleStates, setToggleStates] = useState<Record<string, boolean>>({
    zvuk: true,
    crt: true,
    alarm: false,
    offline: false,
  });

  const handleButtonPress = (id: string) => {
    setActiveButtons((prev) => ({ ...prev, [id]: !prev[id] }));
  };

  const handleToggle = (id: string) => {
    setToggleStates((prev) => ({ ...prev, [id]: !prev[id] }));
  };

  return (
    <div
      className="relative w-full"
      style={{
        background: 'linear-gradient(180deg, #d8d0b8 0%, #d4ccb0 20%, #cec6aa 100%)',
        borderTop: '1px solid #e0d8c0',
        borderBottom: '2px solid #a8a088',
        boxShadow: 'inset 0 1px 0 rgba(255,255,255,0.3), inset 0 -1px 0 rgba(0,0,0,0.1)',
        padding: '16px 20px',
        minHeight: '130px',
      }}
    >
      {/* Subtle surface texture */}
      <div
        className="absolute inset-0 pointer-events-none"
        style={{
          backgroundImage: `url("data:image/svg+xml,%3Csvg width='6' height='6' viewBox='0 0 6 6' xmlns='http://www.w3.org/2000/svg'%3E%3Crect x='0' y='0' width='1' height='1' fill='rgba(0,0,0,0.02)'/%3E%3Crect x='3' y='3' width='1' height='1' fill='rgba(255,255,255,0.02)'/%3E%3C/svg%3E")`,
          backgroundSize: '6px 6px',
        }}
      />

      <div className="relative flex items-start" style={{ gap: '24px' }}>
        {/* ── Title section (far left) ── */}
        <div
          className="shrink-0 flex flex-col justify-center"
          style={{ minWidth: '130px', paddingTop: '2px' }}
        >
          <h2
            style={{
              fontFamily: 'var(--font-mono)',
              fontSize: '26px',
              fontWeight: 700,
              color: '#1a1a1a',
              lineHeight: 1,
              letterSpacing: '-0.01em',
            }}
          >
            Кондуктер
          </h2>
          <span
            style={{
              fontFamily: 'var(--font-mono)',
              fontSize: '11px',
              fontWeight: 600,
              color: '#3a3a3a',
              letterSpacing: '0.12em',
              marginTop: '2px',
            }}
          >
            УПРАВЛЕНИЕ
          </span>
          <span
            style={{
              fontFamily: 'var(--font-mono)',
              fontSize: '8px',
              fontWeight: 500,
              color: '#888',
              letterSpacing: '0.06em',
              marginTop: '4px',
              textTransform: 'uppercase',
            }}
          >
            CONTROLS &middot; OVLÁDANIE &middot; KONTROLE
          </span>
        </div>

        {/* ── Button grid (center-left) ── */}
        <div className="flex flex-col" style={{ gap: '6px' }}>
          {/* Row 1 */}
          <div className="flex" style={{ gap: '6px' }}>
            {buttons.slice(0, 4).map((btn, i) => (
              <PhysicalButton
                key={btn.id}
                btn={btn}
                index={i}
                active={!!activeButtons[btn.id]}
                onPress={() => handleButtonPress(btn.id)}
              />
            ))}
          </div>
          {/* Row 2 */}
          <div className="flex" style={{ gap: '6px' }}>
            {buttons.slice(4, 8).map((btn, i) => (
              <PhysicalButton
                key={btn.id}
                btn={btn}
                index={i + 4}
                active={!!activeButtons[btn.id]}
                onPress={() => handleButtonPress(btn.id)}
              />
            ))}
          </div>
        </div>

        {/* ── Toggle switches section (center-right) ── */}
        <div
          className="shrink-0 flex items-start"
          style={{
            background: 'linear-gradient(180deg, #c4bc9e 0%, #beb6a0 50%, #c4bc9e 100%)',
            borderRadius: '4px',
            padding: '10px 14px',
            gap: '14px',
            border: '1px solid #a8a088',
            boxShadow: 'inset 0 2px 4px rgba(0,0,0,0.08), inset 0 -1px 0 rgba(255,255,255,0.15)',
          }}
        >
          {toggleSwitches.map((toggle) => (
            <ToggleSwitch
              key={toggle.id}
              toggle={toggle}
              active={!!toggleStates[toggle.id]}
              onToggle={() => handleToggle(toggle.id)}
            />
          ))}
        </div>

        {/* ── Logout button (far right) ── */}
        <div className="shrink-0 flex items-center" style={{ alignSelf: 'center' }}>
          <motion.button
            whileTap={{ scale: 0.96 }}
            whileHover={{ scale: 1.02 }}
            style={{
              background: 'linear-gradient(180deg, #3a3a34 0%, #2a2a24 50%, #222 100%)',
              border: '1px solid #111',
              borderRadius: '20px',
              padding: '12px 16px',
              cursor: 'pointer',
              display: 'flex',
              flexDirection: 'column',
              alignItems: 'center',
              gap: '4px',
              boxShadow: '0 2px 6px rgba(0,0,0,0.3), inset 0 1px 0 rgba(255,255,255,0.06)',
              minWidth: '90px',
            }}
          >
            {/* Power icon */}
            <span style={{ fontSize: '16px', color: '#CD2500', lineHeight: 1 }}>&#x23FB;</span>
            <span
              style={{
                fontSize: '7px',
                fontWeight: 600,
                color: '#ccc',
                fontFamily: 'var(--font-mono)',
                textAlign: 'center',
                lineHeight: 1.3,
                letterSpacing: '0.04em',
              }}
            >
              LOGOUT &middot; ODHLÁSIŤ
            </span>
            <span
              style={{
                fontSize: '7px',
                fontWeight: 500,
                color: '#999',
                fontFamily: 'var(--font-mono)',
                textAlign: 'center',
                lineHeight: 1.2,
              }}
            >
              ОДЈАВА &middot; ВЫХОД
            </span>
          </motion.button>
        </div>
      </div>
    </div>
  );
}

// src/components/modules/Kondukter.svelte
<script>
  import Toggle from '../ui/Toggle.svelte';
  import Led from '../ui/Led.svelte';

  let offline = $state(true);
  let zvuk = $state(false);
  let crt = $state(true);
  let alarm = $state(false);

  const buttons = [
    { sk: 'ZÁSOBY', sr: 'ЗАЛИХЕ', led: 'green' },
    { sk: 'MAPA', sr: 'КАРТА', led: 'green' },
    { sk: 'PLATO', sr: 'ПЛАТО', led: 'amber' },
    { sk: 'ZÁHRADA', sr: 'БАШТА', led: 'green' },
    { sk: 'SPRIEVODCA', sr: 'ВОДИЧ', led: 'green' },
    { sk: 'ČLENOVIA', sr: 'ЧЛАНОВИ', led: 'amber' },
    { sk: 'NÁVRHY', sr: 'ПРЕДЛОЗИ', led: 'green' },
    { sk: 'POPLACH', sr: 'УЗБУНА', led: 'red', danger: true },
  ];
</script>

<div class="kondukter-panel">
  <!-- Title section -->
  <div class="kondukter-title-section">
    <div class="kondukter-title">Кондуктер</div>
    <div class="kondukter-subtitle">УПРАВЛЕНИЕ</div>
    <div class="kondukter-tertiary">CONTROLS · OVLÁDANIE · KONTROLE</div>
  </div>

  <!-- Button grid -->
  <div class="kondukter-btn-grid">
    {#each buttons as btn}
      <div class="kondukter-btn-cell">
        <button class="kondukter-btn" class:kondukter-btn-danger={btn.danger}>
          <span class="kondukter-btn-icon">{btn.danger ? '▲' : '◉'}</span>
          <div class="kondukter-btn-labels">
            <span class="kondukter-btn-sk">{btn.sk}</span>
            <span class="kondukter-btn-sr">{btn.sr}</span>
          </div>
        </button>
        <div class="kondukter-led-dot" class:led-green={btn.led === 'green'} class:led-amber={btn.led === 'amber'} class:led-red={btn.led === 'red'}></div>
      </div>
    {/each}
  </div>

  <!-- Toggle switches section -->
  <div class="kondukter-toggles-section">
    <div class="kondukter-toggle-labels-top">
      <span>ZVUK<br><small>ЗВУК</small></span>
      <span>CRT<br><small>ЕКРАН</small></span>
      <span>ALARM<br><small>АЛАРМ</small></span>
      <span>OFFLINE<br><small>ОФЛАЈН</small></span>
    </div>
    <div class="kondukter-toggles-row">
      <Toggle bind:on={zvuk} />
      <Toggle bind:on={crt} />
      <Toggle bind:on={alarm} />
      <Toggle bind:on={offline} />
    </div>
    <div class="kondukter-toggle-labels-bottom">
      <span>OFFLINE<br><small>ОФЛАЈН</small></span>
      <span>CRT<br><small>ЕКРАН</small></span>
      <span>ALARM<br><small>АЛАРМ</small></span>
      <span>OFFLINE<br><small>ОФЛАЈН</small></span>
    </div>
  </div>

  <!-- Logout button -->
  <div class="kondukter-logout-section">
    <button class="kondukter-logout-btn">
      <span class="kondukter-logout-icon">⏻</span>
      <div class="kondukter-logout-labels">
        <span>LOGOUT · ODHLÁSIŤ</span>
        <span class="kondukter-logout-sr">ОДЈАВА · ВЫХОД</span>
      </div>
    </button>
  </div>
</div>

<style>
  /* Panel container - horizontal rack module layout */
  .kondukter-panel {
    display: flex;
    align-items: stretch;
    background:
      repeating-conic-gradient(rgba(0,0,0,0.015) 0% 25%, transparent 0% 50%) 0 0 / 4px 4px,
      linear-gradient(180deg, #e8dcc8 0%, #ddd0b8 50%, #d5c8aa 100%);
    border: 3px solid var(--panel-700, #3A3F2C);
    border-radius: var(--radius, 2px);
    box-shadow:
      inset 3px 3px 0 var(--bevel-light, rgba(255,255,255,0.35)),
      inset -3px -3px 0 var(--bevel-dark, rgba(0,0,0,0.45)),
      0 4px 11px rgba(0,0,0,0.35);
    padding: 16px 20px;
    gap: 20px;
    min-height: 140px;
    position: relative;
  }

  /* Screw dots */
  .kondukter-panel::before {
    content: '';
    position: absolute;
    top: 8px;
    right: 8px;
    width: 8px;
    height: 8px;
    border-radius: 50%;
    background: var(--bakelite, #2a2419);
    box-shadow:
      0 calc(100% - 8px) 0 var(--bakelite, #2a2419);
  }

  /* Title section - left side */
  .kondukter-title-section {
    display: flex;
    flex-direction: column;
    justify-content: center;
    padding-right: 16px;
    border-right: 1px dashed var(--panel-600, #50533C);
    min-width: 140px;
    flex-shrink: 0;
  }

  .kondukter-title {
    font-family: var(--font-mono, 'IBM Plex Mono', monospace);
    font-size: clamp(22px, 2.2vw, 32px);
    font-weight: 700;
    color: var(--panel-800, #2C2E25);
    letter-spacing: 1px;
    line-height: 1.1;
  }

  .kondukter-subtitle {
    font-family: var(--font-mono, 'IBM Plex Mono', monospace);
    font-size: clamp(10px, 0.9vw, 13px);
    font-weight: 500;
    color: var(--panel-600, #50533C);
    letter-spacing: 2px;
    margin-top: 4px;
  }

  .kondukter-tertiary {
    font-family: var(--font-tech, 'Share Tech Mono', monospace);
    font-size: clamp(8px, 0.7vw, 10px);
    color: var(--panel-600, #50533C);
    letter-spacing: 1px;
    margin-top: 3px;
  }

  /* Button grid - center */
  .kondukter-btn-grid {
    display: grid;
    grid-template-columns: repeat(4, 1fr);
    grid-template-rows: repeat(2, 1fr);
    gap: 10px;
    flex: 1;
    align-content: center;
  }

  .kondukter-btn-cell {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 5px;
  }

  .kondukter-btn {
    display: flex;
    align-items: center;
    gap: 6px;
    background: linear-gradient(180deg, #f5f0e8 0%, #e8dcc8 40%, #d8ccb0 100%);
    color: var(--panel-800, #2C2E25);
    border: 2px solid #999;
    border-color: #bbb #888 #777 #aaa;
    border-radius: 3px;
    padding: 8px 10px;
    font-family: var(--font-mono, 'IBM Plex Mono', monospace);
    font-size: clamp(9px, 0.8vw, 12px);
    font-weight: 700;
    letter-spacing: 0.8px;
    text-transform: uppercase;
    cursor: pointer;
    min-width: 110px;
    min-height: 48px;
    box-shadow:
      0 3px 0 #999,
      0 4px 6px rgba(0,0,0,0.25),
      inset 0 1px 0 rgba(255,255,255,0.7),
      inset 0 -1px 0 rgba(0,0,0,0.15);
    transition: all 80ms ease-out;
    position: relative;
    text-align: left;
    line-height: 1.15;
  }

  .kondukter-btn:hover {
    background: linear-gradient(180deg, #fff 0%, #f0e8d8 40%, #e0d4be 100%);
    transform: translateY(-1px);
    box-shadow:
      0 4px 0 #999,
      0 5px 8px rgba(0,0,0,0.3),
      inset 0 1px 0 rgba(255,255,255,0.7),
      inset 0 -1px 0 rgba(0,0,0,0.15);
  }

  .kondukter-btn:active {
    transform: translateY(2px);
    box-shadow:
      0 1px 0 #999,
      inset 0 2px 4px rgba(0,0,0,0.3);
  }

  .kondukter-btn-danger {
    background: linear-gradient(180deg, #d44 0%, #b22222 40%, #8b1a1a 100%);
    color: var(--cream, #E8DCC8);
    border-color: #c44 #811 #711 #a33;
    box-shadow:
      0 3px 0 #611,
      0 4px 6px rgba(0,0,0,0.35),
      inset 0 1px 0 rgba(255,255,255,0.3),
      inset 0 -1px 0 rgba(0,0,0,0.3);
  }

  .kondukter-btn-danger:hover {
    background: linear-gradient(180deg, #e55 0%, #c33 40%, #a22 100%);
  }

  .kondukter-btn-danger .kondukter-btn-sr {
    color: rgba(232, 220, 200, 0.7);
  }

  .kondukter-btn-icon {
    font-size: 0.8em;
    flex-shrink: 0;
  }

  .kondukter-btn-labels {
    display: flex;
    flex-direction: column;
    gap: 1px;
  }

  .kondukter-btn-sk {
    font-size: 1em;
  }

  .kondukter-btn-sr {
    font-size: 0.78em;
    color: var(--panel-600, #50533C);
    font-weight: 500;
    letter-spacing: 0.8px;
  }

  /* LED dots below buttons */
  .kondukter-led-dot {
    width: 7px;
    height: 7px;
    border-radius: 50%;
    background: #333;
    box-shadow: inset 0 0 2px rgba(0,0,0,0.5);
  }

  .kondukter-led-dot.led-green {
    background: radial-gradient(circle at 35% 35%, #aaffaa, #33cc33 60%, #228822);
    box-shadow: 0 0 4px #33cc33, 0 0 8px rgba(51,204,51,0.4);
  }

  .kondukter-led-dot.led-amber {
    background: radial-gradient(circle at 35% 35%, #ffdd88, #e6a817 60%, #aa7711);
    box-shadow: 0 0 4px #e6a817, 0 0 8px rgba(230,168,23,0.4);
  }

  .kondukter-led-dot.led-red {
    background: radial-gradient(circle at 35% 35%, #ff8866, #cd2500 60%, #881100);
    box-shadow: 0 0 4px #cd2500, 0 0 8px rgba(205,37,0,0.4);
  }

  /* Toggle switches section - recessed dark area */
  .kondukter-toggles-section {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    gap: 4px;
    background:
      linear-gradient(180deg, rgba(0,0,0,0.06) 0%, rgba(0,0,0,0.03) 50%, rgba(0,0,0,0.06) 100%);
    border: 1px solid var(--panel-600, #50533C);
    border-radius: 3px;
    padding: 10px 14px;
    box-shadow: inset 0 1px 4px rgba(0,0,0,0.15);
    flex-shrink: 0;
  }

  .kondukter-toggle-labels-top,
  .kondukter-toggle-labels-bottom {
    display: flex;
    gap: 16px;
    justify-content: space-around;
    width: 100%;
  }

  .kondukter-toggle-labels-top span,
  .kondukter-toggle-labels-bottom span {
    font-family: var(--font-tech, 'Share Tech Mono', monospace);
    font-size: 9px;
    color: var(--panel-700, #3A3F2C);
    letter-spacing: 1px;
    text-align: center;
    line-height: 1.2;
    min-width: 50px;
  }

  .kondukter-toggle-labels-top small,
  .kondukter-toggle-labels-bottom small {
    font-family: var(--font-mono, 'IBM Plex Mono', monospace);
    font-size: 8px;
    color: var(--panel-600, #50533C);
    letter-spacing: 0.5px;
  }

  .kondukter-toggles-row {
    display: flex;
    gap: 16px;
    align-items: center;
  }

  /* Logout section - far right */
  .kondukter-logout-section {
    display: flex;
    align-items: center;
    flex-shrink: 0;
  }

  .kondukter-logout-btn {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    gap: 6px;
    background: linear-gradient(180deg, var(--panel-700, #3A3F2C) 0%, var(--panel-800, #2C2E25) 100%);
    color: var(--cream, #E8DCC8);
    border: 3px solid var(--panel-800, #2C2E25);
    border-radius: 3px;
    padding: 14px 16px;
    min-height: 100%;
    cursor: pointer;
    box-shadow:
      inset 1px 1px 0 rgba(255,255,255,0.15),
      inset -1px -1px 0 rgba(0,0,0,0.3),
      0 3px 0 rgba(0,0,0,0.5),
      0 4px 8px rgba(0,0,0,0.4);
    transition: all 80ms ease-out;
    font-family: var(--font-mono, 'IBM Plex Mono', monospace);
    font-size: clamp(8px, 0.75vw, 11px);
    font-weight: 700;
    letter-spacing: 1px;
    text-transform: uppercase;
    text-align: center;
    line-height: 1.3;
    min-width: 90px;
  }

  .kondukter-logout-btn:hover {
    background: linear-gradient(180deg, var(--panel-800, #2C2E25) 0%, #1a1c15 100%);
  }

  .kondukter-logout-btn:active {
    transform: translateY(2px);
    box-shadow: inset 0 2px 4px rgba(0,0,0,0.5);
  }

  .kondukter-logout-icon {
    font-size: 18px;
  }

  .kondukter-logout-labels {
    display: flex;
    flex-direction: column;
    gap: 2px;
  }

  .kondukter-logout-sr {
    font-size: 0.85em;
    color: rgba(232, 220, 200, 0.6);
    font-weight: 500;
  }
</style>
