// src/components/modules/Operator.svelte
<script>
  const members = [
    { initials: 'JM', name: 'JOZEF\nMICHALEK', role: 'OVERLORD', isOverlord: true },
    { initials: 'JD', name: 'JANKO\nDRAGOVIC', role: 'OPERATER', isOverlord: false },
    { initials: 'MM', name: 'MARKO\nMIJATOVIC', role: 'OPERATER', isOverlord: false },
    { initials: 'IK', name: 'IGOR\nKADIC', role: 'OPERATER', isOverlord: false },
  ];
</script>

<div class="op-panel">
  <!-- Corner screws -->
  <div class="screw screw-tl"></div>
  <div class="screw screw-tr"></div>
  <div class="screw screw-bl"></div>
  <div class="screw screw-br"></div>

  <!-- LEFT SECTION: Title + readouts -->
  <div class="op-left">
    <div class="op-date">1·2·1983</div>
    <div class="op-title">ОПЕРАТОР</div>
    <div class="op-subtitle">OPERATOR · OPERÁTOR · OPERATER</div>

    <!-- Red LED readouts with labels on the right -->
    <div class="op-readouts">
      <div class="op-readout-row">
        <div class="op-readout-display">888888</div>
        <div class="op-readout-indicator">S</div>
        <div class="op-readout-label">
          <span class="op-lbl-main">KÓD</span>
          <span class="op-lbl-cyr">КОД</span>
        </div>
      </div>
      <div class="op-readout-row">
        <div class="op-readout-display">888888</div>
        <div class="op-readout-indicator">S</div>
        <div class="op-readout-label">
          <span class="op-lbl-main">ROLA</span>
          <span class="op-lbl-cyr">УЛОГА</span>
        </div>
      </div>
      <div class="op-readout-row">
        <div class="op-readout-display">888888</div>
        <div class="op-readout-indicator">S</div>
        <div class="op-readout-label">
          <span class="op-lbl-main">STAV</span>
          <span class="op-lbl-cyr">СТАЊЕ</span>
        </div>
      </div>
    </div>

    <!-- Bottom: KOD small readout + UPLINK knob -->
    <div class="op-bottom-section">
      <div class="op-bottom-row">
        <div class="op-bottom-label">
          <span class="op-lbl-main">KÓD</span>
          <span class="op-lbl-cyr">КОД</span>
        </div>
        <div class="op-bottom-display">888888</div>
      </div>
      <div class="op-uplink-row">
        <div class="op-uplink-label">
          <span class="op-lbl-main">UPLINK</span>
          <span class="op-lbl-cyr">ВЕЗЕ</span>
        </div>
        <div class="op-knob-small-wrap">
          <div class="op-knob-small">
            <div class="op-knob-small-ring"></div>
          </div>
          <div class="op-knob-small">
            <div class="op-knob-small-ring"></div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Vertical divider line -->
  <div class="op-divider"></div>

  <!-- RIGHT SECTION: 4 Member columns -->
  <div class="op-members">
    {#each members as member}
      <div class="op-member-col">
        <div class="op-member-name">{@html member.name.replace('\n', '<br>')}</div>
        <div class="op-member-status">
          <span>ČAKÁ NA AKTIVÁCIU</span>
          <span>ЧЕКА ЧЛАНА</span>
        </div>
        <div class="op-member-badge">{member.initials}</div>

        <!-- Large chrome rotary knob -->
        <div class="op-knob">
          <div class="op-knob-outer">
            <div class="op-knob-ring">
              <div class="op-knob-cap">
                <div class="op-knob-line"></div>
              </div>
            </div>
          </div>
        </div>

        <div class="op-member-role" class:op-role-overlord={member.isOverlord}>
          {member.role}
        </div>
      </div>
    {/each}
  </div>
</div>

<style>
  /* ======== OPERATOR PANEL ======== */
  .op-panel {
    background:
      repeating-linear-gradient(
        90deg,
        rgba(255,255,255,0.04) 0px,
        rgba(255,255,255,0.07) 1px,
        transparent 1px,
        transparent 4px
      ),
      repeating-linear-gradient(
        0deg,
        rgba(0,0,0,0.02) 0px,
        transparent 1px,
        transparent 8px
      ),
      linear-gradient(170deg,
        #8494a4 0%,
        #6d7f8f 15%,
        #5a6e7e 35%,
        #4e6272 55%,
        #566a7a 75%,
        #6a7a8a 100%
      );
    border: 3px solid #3a4856;
    border-top-color: #8494a4;
    border-left-color: #7a8a9a;
    border-radius: 4px;
    padding: 20px 28px 18px;
    box-shadow:
      inset 2px 2px 0 rgba(255,255,255,0.18),
      inset -2px -2px 0 rgba(0,0,0,0.25),
      0 6px 20px rgba(0,0,0,0.5),
      0 2px 4px rgba(0,0,0,0.3);
    position: relative;
    display: grid;
    grid-template-columns: 240px 1px 1fr;
    gap: 14px;
    min-width: 0;
    overflow: hidden;
  }

  /* Horizontal ridge line across the panel (like in the design) */
  .op-panel::after {
    content: '';
    position: absolute;
    bottom: 0;
    left: 0;
    right: 0;
    height: 8px;
    background: linear-gradient(to bottom,
      rgba(0,0,0,0.15),
      rgba(0,0,0,0.08) 40%,
      rgba(255,255,255,0.1) 50%,
      rgba(0,0,0,0.1)
    );
    pointer-events: none;
  }

  /* ======== SCREWS ======== */
  .screw {
    position: absolute;
    width: 18px;
    height: 18px;
    border-radius: 50%;
    background: radial-gradient(circle at 35% 30%,
      #e8e4dc, #c8c4bc 30%, #a8a49c 55%, #8a8680 80%, #706c66 100%);
    border: 1px solid rgba(0,0,0,0.4);
    box-shadow:
      inset 0 1px 3px rgba(255,255,255,0.6),
      inset 0 -1px 2px rgba(0,0,0,0.3),
      0 2px 4px rgba(0,0,0,0.5);
    z-index: 2;
  }
  .screw::before {
    content: '';
    position: absolute;
    top: 50%;
    left: 50%;
    width: 11px;
    height: 1.5px;
    background: linear-gradient(to right,
      rgba(0,0,0,0.5), rgba(0,0,0,0.15), rgba(0,0,0,0.5));
    transform: translate(-50%, -50%) rotate(30deg);
    border-radius: 1px;
  }
  .screw::after {
    content: '';
    position: absolute;
    top: 50%;
    left: 50%;
    width: 11px;
    height: 1.5px;
    background: linear-gradient(to right,
      rgba(0,0,0,0.5), rgba(0,0,0,0.15), rgba(0,0,0,0.5));
    transform: translate(-50%, -50%) rotate(-60deg);
    border-radius: 1px;
  }
  .screw-tl { top: 8px; left: 8px; }
  .screw-tr { top: 8px; right: 8px; }
  .screw-bl { bottom: 8px; left: 8px; }
  .screw-br { bottom: 8px; right: 8px; }

  /* ======== LEFT SECTION ======== */
  .op-left {
    display: flex;
    flex-direction: column;
    gap: 4px;
    min-width: 0;
  }

  .op-date {
    font-family: 'Georgia', 'Times New Roman', serif;
    font-style: italic;
    font-size: 12px;
    color: rgba(255,255,255,0.5);
    letter-spacing: 0.5px;
  }

  .op-title {
    font-family: var(--font-mono, 'IBM Plex Mono', monospace);
    font-size: clamp(28px, 3.2vw, 42px);
    font-weight: 800;
    color: #ffffff;
    letter-spacing: 4px;
    line-height: 1;
    text-shadow: 0 2px 6px rgba(0,0,0,0.5);
    margin-bottom: 1px;
  }

  .op-subtitle {
    font-family: var(--font-tech, 'Share Tech Mono', monospace);
    font-size: 8.5px;
    color: rgba(255,255,255,0.45);
    letter-spacing: 2px;
    margin-bottom: 8px;
  }

  /* ======== RED LED READOUTS ======== */
  .op-readouts {
    display: flex;
    flex-direction: column;
    gap: 3px;
  }

  .op-readout-row {
    display: flex;
    align-items: center;
    gap: 3px;
  }

  .op-readout-display {
    background: #0e0604;
    border: 2px solid #1a0e0a;
    border-radius: 2px;
    padding: 2px 6px;
    font-family: var(--font-lcd7, 'DSEG7 Classic', monospace);
    font-size: 17px;
    color: #ff3333;
    text-shadow: 0 0 8px #ff3333, 0 0 16px rgba(255,51,51,0.3);
    letter-spacing: 2px;
    min-width: 105px;
    box-shadow:
      inset 0 0 10px rgba(0,0,0,0.9),
      inset 0 1px 3px rgba(0,0,0,0.5),
      0 1px 2px rgba(0,0,0,0.3);
  }

  .op-readout-indicator {
    width: 14px;
    height: 14px;
    background: #0e0604;
    border: 1px solid #1a0e0a;
    border-radius: 2px;
    display: flex;
    align-items: center;
    justify-content: center;
    font-family: var(--font-lcd14, 'DSEG14 Classic', monospace);
    font-size: 9px;
    color: #ff3333;
    text-shadow: 0 0 4px #ff3333;
    box-shadow: inset 0 0 5px rgba(0,0,0,0.8);
  }

  .op-readout-label {
    display: flex;
    flex-direction: column;
    margin-left: 4px;
    min-width: 38px;
  }

  .op-lbl-main {
    font-family: var(--font-tech, 'Share Tech Mono', monospace);
    font-size: 8.5px;
    color: rgba(255,255,255,0.6);
    letter-spacing: 1.2px;
    line-height: 1.15;
    text-transform: uppercase;
  }

  .op-lbl-cyr {
    font-family: var(--font-mono, 'IBM Plex Mono', monospace);
    font-size: 7.5px;
    color: rgba(255,255,255,0.35);
    letter-spacing: 0.8px;
    line-height: 1.15;
  }

  /* ======== DIVIDER ======== */
  .op-divider {
    width: 1px;
    background: linear-gradient(to bottom,
      transparent 5%,
      rgba(255,255,255,0.12) 20%,
      rgba(255,255,255,0.08) 80%,
      transparent 95%
    );
    align-self: stretch;
  }

  /* ======== BOTTOM LEFT: KOD + UPLINK ======== */
  .op-bottom-section {
    margin-top: auto;
    display: flex;
    flex-direction: column;
    gap: 5px;
    padding-top: 6px;
  }

  .op-bottom-row {
    display: flex;
    align-items: center;
    gap: 6px;
  }

  .op-bottom-label {
    display: flex;
    flex-direction: column;
  }

  .op-bottom-display {
    background: #0e0604;
    border: 2px solid #1a0e0a;
    border-radius: 2px;
    padding: 1px 5px;
    font-family: var(--font-lcd7, 'DSEG7 Classic', monospace);
    font-size: 11px;
    color: #ff3333;
    text-shadow: 0 0 4px #ff3333;
    letter-spacing: 1px;
    box-shadow: inset 0 0 6px rgba(0,0,0,0.8);
  }

  .op-uplink-row {
    display: flex;
    align-items: center;
    gap: 8px;
  }

  .op-uplink-label {
    display: flex;
    flex-direction: column;
  }

  .op-knob-small-wrap {
    display: flex;
    gap: 8px;
    align-items: center;
  }

  /* ======== SMALL KNOBS (uplink) ======== */
  .op-knob-small {
    width: 30px;
    height: 30px;
    border-radius: 50%;
    background: radial-gradient(circle at 30% 25%,
      #4a4a4a, #1e1e1e 75%);
    border: 2px solid #3a3a3a;
    box-shadow:
      0 2px 6px rgba(0,0,0,0.6),
      inset 0 1px 1px rgba(255,255,255,0.08);
    display: flex;
    align-items: center;
    justify-content: center;
  }

  .op-knob-small-ring {
    width: 18px;
    height: 18px;
    border-radius: 50%;
    background: radial-gradient(circle at 40% 30%,
      #888, #555 50%, #3a3a3a 100%);
    border: 1px solid #555;
    box-shadow: inset 0 1px 2px rgba(255,255,255,0.25);
  }

  /* ======== MEMBER COLUMNS ======== */
  .op-members {
    display: grid;
    grid-template-columns: repeat(4, 1fr);
    gap: 6px;
    min-width: 0;
    align-self: stretch;
  }

  .op-member-col {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 4px;
    padding: 8px 4px 6px;
    background: rgba(0,0,0,0.06);
    border-radius: 2px;
    border: 1px solid rgba(255,255,255,0.04);
    min-width: 0;
  }

  .op-member-name {
    font-family: var(--font-mono, 'IBM Plex Mono', monospace);
    font-size: clamp(8px, 0.9vw, 11px);
    font-weight: 700;
    color: #fff;
    letter-spacing: 1px;
    text-align: center;
    line-height: 1.2;
    text-shadow: 0 1px 3px rgba(0,0,0,0.5);
  }

  .op-member-status {
    display: flex;
    flex-direction: column;
    align-items: center;
    font-family: var(--font-tech, 'Share Tech Mono', monospace);
    font-size: 6.5px;
    color: rgba(255,255,255,0.38);
    letter-spacing: 0.6px;
    text-align: center;
    line-height: 1.3;
    gap: 0;
  }

  .op-member-badge {
    width: 34px;
    height: 34px;
    border-radius: 50%;
    background: linear-gradient(145deg, #1e2848, #141c38);
    border: 2px solid rgba(200,200,200,0.15);
    display: flex;
    align-items: center;
    justify-content: center;
    font-family: var(--font-mono, 'IBM Plex Mono', monospace);
    font-weight: 700;
    font-size: 12px;
    color: rgba(255,255,255,0.65);
    box-shadow:
      inset 0 2px 5px rgba(0,0,0,0.6),
      0 1px 3px rgba(0,0,0,0.4);
    letter-spacing: 0.5px;
  }

  /* ======== LARGE CHROME ROTARY KNOB ======== */
  .op-knob {
    width: 50px;
    height: 50px;
    display: flex;
    align-items: center;
    justify-content: center;
    flex-shrink: 0;
  }

  .op-knob-outer {
    width: 48px;
    height: 48px;
    border-radius: 50%;
    background: radial-gradient(circle at 30% 25%,
      #3a3a3a, #181818 80%);
    border: 2px solid #404040;
    box-shadow:
      0 4px 10px rgba(0,0,0,0.7),
      0 1px 3px rgba(0,0,0,0.5),
      inset 0 1px 1px rgba(255,255,255,0.05);
    display: flex;
    align-items: center;
    justify-content: center;
  }

  .op-knob-ring {
    width: 38px;
    height: 38px;
    border-radius: 50%;
    background: conic-gradient(
      from 0deg,
      #7a7a7a 0deg,
      #b8b8b8 20deg,
      #8a8a8a 45deg,
      #cccccc 70deg,
      #999999 95deg,
      #dddddd 120deg,
      #aaaaaa 145deg,
      #cccccc 170deg,
      #888888 195deg,
      #bbbbbb 220deg,
      #999999 245deg,
      #dddddd 270deg,
      #aaaaaa 295deg,
      #bbbbbb 320deg,
      #888888 345deg,
      #7a7a7a 360deg
    );
    border: 1px solid rgba(100,100,100,0.6);
    box-shadow:
      inset 0 0 6px rgba(0,0,0,0.25),
      0 1px 3px rgba(0,0,0,0.3);
    display: flex;
    align-items: center;
    justify-content: center;
  }

  .op-knob-cap {
    width: 20px;
    height: 20px;
    border-radius: 50%;
    background: radial-gradient(circle at 40% 35%,
      #f0f0f0, #c0c0c0 40%, #909090 80%, #787878 100%);
    border: 1px solid rgba(100,100,100,0.5);
    box-shadow:
      inset 0 1px 4px rgba(255,255,255,0.7),
      inset 0 -1px 2px rgba(0,0,0,0.25);
    position: relative;
  }

  .op-knob-line {
    position: absolute;
    top: 2px;
    left: 50%;
    transform: translateX(-50%);
    width: 2px;
    height: 6px;
    border-radius: 1px;
    background: #444;
  }

  /* ======== ROLE BADGES ======== */
  .op-member-role {
    font-family: var(--font-mono, 'IBM Plex Mono', monospace);
    font-size: clamp(7px, 0.75vw, 9px);
    font-weight: 700;
    letter-spacing: 1.5px;
    color: rgba(255,255,255,0.55);
    background: rgba(0,0,0,0.2);
    padding: 3px 8px;
    border-radius: 2px;
    border: 1px solid rgba(255,255,255,0.08);
    text-align: center;
    white-space: nowrap;
  }

  .op-role-overlord {
    background: #b22222;
    color: #fff;
    border-color: rgba(220,60,60,0.5);
    box-shadow: 0 0 8px rgba(178,34,34,0.35);
    text-shadow: 0 1px 2px rgba(0,0,0,0.4);
  }

  /* ======== RESPONSIVE ======== */
  @media (max-width: 900px) {
    .op-panel {
      grid-template-columns: 1fr;
    }
    .op-divider {
      width: auto;
      height: 1px;
      background: linear-gradient(to right,
        transparent 5%,
        rgba(255,255,255,0.12) 20%,
        rgba(255,255,255,0.08) 80%,
        transparent 95%
      );
    }
    .op-members {
      grid-template-columns: repeat(2, 1fr);
    }
  }

  @media (max-width: 500px) {
    .op-members {
      grid-template-columns: 1fr 1fr;
    }
    .op-panel {
      padding: 16px 14px;
    }
  }
</style>

// src/components/modules/Operator.tsx
'use client';

import { useState } from 'react';
import { motion } from 'framer-motion';

/* ── tiny sub-components ── */

function ChromeScrew({ className }: { className?: string }) {
  return (
    <div
      className={`absolute z-10 ${className}`}
      style={{
        width: 18,
        height: 18,
        borderRadius: '50%',
        background: 'radial-gradient(circle at 35% 35%, #e8e8e8, #888 50%, #555 100%)',
        boxShadow: 'inset 0 1px 2px rgba(255,255,255,0.5), 0 1px 3px rgba(0,0,0,0.6)',
      }}
    >
      <div
        style={{
          position: 'absolute',
          top: '50%',
          left: '25%',
          right: '25%',
          height: 1.5,
          background: '#444',
          transform: 'translateY(-50%) rotate(35deg)',
          borderRadius: 1,
        }}
      />
    </div>
  );
}

function LedReadout({ label, labelCyrillic, value }: { label: string; labelCyrillic: string; value: string }) {
  return (
    <div className="flex items-center gap-2 mb-1">
      <div
        style={{
          background: '#0c0c0c',
          borderRadius: 2,
          padding: '2px 8px',
          border: '1px solid #333',
          boxShadow: 'inset 0 1px 4px rgba(0,0,0,0.8)',
          minWidth: 130,
        }}
      >
        <div
          style={{
            fontFamily: "'DSEG7 Classic', 'VT323', monospace",
            fontSize: 22,
            color: '#ff3333',
            textShadow: '0 0 8px #ff3333, 0 0 20px rgba(255,50,50,0.3)',
            letterSpacing: 2,
            lineHeight: 1.2,
          }}
        >
          {value}
        </div>
      </div>
      <div
        className="flex items-center gap-1"
        style={{
          fontSize: 8,
          fontFamily: "'IBM Plex Mono', monospace",
          color: '#ddd',
          fontWeight: 600,
          letterSpacing: 1,
          textTransform: 'uppercase',
          lineHeight: 1.1,
        }}
      >
        <div
          style={{
            width: 8,
            height: 8,
            background: '#ff3333',
            borderRadius: '50%',
            boxShadow: '0 0 4px #ff3333',
            flexShrink: 0,
          }}
        />
        <div>
          <div>{label}</div>
          <div style={{ color: '#aaa', fontSize: 7 }}>{labelCyrillic}</div>
        </div>
      </div>
    </div>
  );
}

function RotaryKnob({ size = 56, initialAngle = 0 }: { size?: number; initialAngle?: number }) {
  const [angle, setAngle] = useState(initialAngle);

  return (
    <motion.div
      style={{
        width: size,
        height: size,
        borderRadius: '50%',
        background: `radial-gradient(circle at 38% 32%, #e0ddd8 0%, #b0aca5 25%, #888580 50%, #5a5856 80%, #3a3836 100%)`,
        boxShadow: `
          0 2px 8px rgba(0,0,0,0.6),
          0 0 0 2px #333,
          inset 0 1px 3px rgba(255,255,255,0.3)
        `,
        cursor: 'grab',
        position: 'relative',
      }}
      animate={{ rotate: angle }}
      whileHover={{ scale: 1.05 }}
      onClick={() => setAngle((a) => a + 30)}
    >
      {/* pointer line */}
      <div
        style={{
          position: 'absolute',
          top: 4,
          left: '50%',
          width: 2,
          height: size / 2 - 6,
          background: '#eee',
          transform: 'translateX(-50%)',
          borderRadius: 1,
          boxShadow: '0 0 2px rgba(255,255,255,0.5)',
        }}
      />
      {/* center cap */}
      <div
        style={{
          position: 'absolute',
          top: '50%',
          left: '50%',
          width: size * 0.3,
          height: size * 0.3,
          borderRadius: '50%',
          background: 'radial-gradient(circle at 40% 35%, #999, #555)',
          transform: 'translate(-50%, -50%)',
        }}
      />
    </motion.div>
  );
}

function MemberColumn({
  name,
  initials,
  role,
  isOverlord = false,
}: {
  name: string;
  initials: string;
  role: string;
  isOverlord?: boolean;
}) {
  return (
    <div className="flex flex-col items-center" style={{ width: 120, gap: 4 }}>
      {/* Name */}
      <div
        style={{
          fontFamily: "'IBM Plex Mono', monospace",
          fontSize: 9,
          fontWeight: 700,
          color: '#fff',
          textAlign: 'center',
          letterSpacing: 1.5,
          textTransform: 'uppercase',
          lineHeight: 1.2,
        }}
      >
        {name}
      </div>

      {/* Status */}
      <div
        style={{
          fontFamily: "'Share Tech Mono', monospace",
          fontSize: 6.5,
          color: '#aab4be',
          textAlign: 'center',
          letterSpacing: 0.5,
          lineHeight: 1.2,
        }}
      >
        CAKA NA AKTIVACIU
        <br />
        CEKA CLANA
      </div>

      {/* Avatar badge */}
      <div
        style={{
          width: 36,
          height: 36,
          borderRadius: '50%',
          background: 'var(--navy, #202867)',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          fontFamily: "'IBM Plex Mono', monospace",
          fontSize: 13,
          fontWeight: 700,
          color: '#c0c8d8',
          border: '2px solid #3a4480',
          boxShadow: '0 2px 6px rgba(0,0,0,0.4)',
          marginTop: 2,
        }}
      >
        {initials}
      </div>

      {/* Rotary knob */}
      <div style={{ marginTop: 4 }}>
        <RotaryKnob size={48} initialAngle={Math.random() * 120 - 60} />
      </div>

      {/* Role label */}
      <div
        style={{
          marginTop: 4,
          padding: '2px 10px',
          fontFamily: "'IBM Plex Mono', monospace",
          fontSize: 8,
          fontWeight: 600,
          letterSpacing: 2,
          textTransform: 'uppercase',
          color: isOverlord ? '#fff' : '#8899aa',
          background: isOverlord ? '#b22222' : 'transparent',
          border: isOverlord ? 'none' : '1px solid #556677',
          borderRadius: 2,
        }}
      >
        {role}
      </div>
    </div>
  );
}

/* ── Main component ── */

export default function Operator() {
  return (
    <div
      className="relative w-full"
      style={{
        background: `
          linear-gradient(180deg, #6b7b8b 0%, #5a6a7a 15%, #4e5e6e 85%, #3d4d5d 100%)
        `,
        backgroundImage: `
          repeating-linear-gradient(
            0deg,
            transparent,
            transparent 2px,
            rgba(255,255,255,0.015) 2px,
            rgba(255,255,255,0.015) 3px
          ),
          linear-gradient(180deg, #6b7b8b 0%, #5a6a7a 15%, #4e5e6e 85%, #3d4d5d 100%)
        `,
        padding: '18px 24px',
        borderTop: '1px solid #8090a0',
        borderBottom: '2px solid #2a3a4a',
        boxShadow: 'inset 0 1px 0 rgba(255,255,255,0.1), inset 0 -1px 0 rgba(0,0,0,0.3), 0 4px 12px rgba(0,0,0,0.5)',
        minHeight: 200,
      }}
    >
      {/* Chrome screws */}
      <ChromeScrew className="top-3 left-3" />
      <ChromeScrew className="top-3 right-3" />
      <ChromeScrew className="bottom-3 left-3" />
      <ChromeScrew className="bottom-3 right-3" />

      {/* Model date top-left */}
      <div
        style={{
          position: 'absolute',
          top: 10,
          left: 32,
          fontFamily: "'Georgia', serif",
          fontStyle: 'italic',
          fontSize: 11,
          color: '#bcc8d4',
          opacity: 0.7,
        }}
      >
        1·2·1983
      </div>

      {/* Title area */}
      <div style={{ marginBottom: 8 }}>
        <div
          style={{
            fontFamily: "'IBM Plex Mono', monospace",
            fontSize: 32,
            fontWeight: 800,
            color: '#ffffff',
            letterSpacing: 4,
            lineHeight: 1,
            textShadow: '0 2px 4px rgba(0,0,0,0.4)',
          }}
        >
          ОПЕРАТОР
        </div>
        <div
          style={{
            fontFamily: "'Share Tech Mono', monospace",
            fontSize: 9,
            color: '#a0b0c0',
            letterSpacing: 3,
            marginTop: 2,
          }}
        >
          OPERATOR · OPERATOR · OPERATER
        </div>
      </div>

      {/* Content: left readouts + right members */}
      <div className="flex gap-4" style={{ marginTop: 4 }}>
        {/* Left section - LED readouts */}
        <div className="flex flex-col" style={{ minWidth: 200, gap: 2 }}>
          <LedReadout label="KOD" labelCyrillic="КОД" value="888888" />
          <LedReadout label="ROLA" labelCyrillic="УЛОГА" value="888888" />
          <LedReadout label="STAV" labelCyrillic="СТАЊЕ" value="888886" />

          {/* KOD readout below */}
          <div className="flex items-center gap-2 mt-2">
            <div
              style={{
                fontFamily: "'IBM Plex Mono', monospace",
                fontSize: 8,
                color: '#ccc',
                letterSpacing: 1,
                fontWeight: 600,
              }}
            >
              KOD
              <br />
              <span style={{ color: '#999', fontSize: 7 }}>КОД</span>
            </div>
          </div>

          {/* UPLINK section */}
          <div className="flex items-center gap-3 mt-2">
            <div>
              <div
                style={{
                  fontFamily: "'Share Tech Mono', monospace",
                  fontSize: 8,
                  color: '#a0b0c0',
                  letterSpacing: 2,
                }}
              >
                UPLINK
              </div>
              <div
                style={{
                  fontFamily: "'Share Tech Mono', monospace",
                  fontSize: 7,
                  color: '#778899',
                  letterSpacing: 1,
                }}
              >
                IP:3A
              </div>
            </div>
            <RotaryKnob size={40} />
          </div>
        </div>

        {/* Right section - Member columns */}
        <div className="flex gap-1 flex-1 justify-end">
          <MemberColumn name="JOZEF MICHALEK" initials="JM" role="OVERLORD" isOverlord />
          <MemberColumn name="JANKO DRAGOVIC" initials="JD" role="OPERATER" />
          <MemberColumn name="MARKO MIJATOVIC" initials="MM" role="OPERATER" />
          <MemberColumn name="IGOR KADIC" initials="IK" role="OPERATER" />
        </div>
      </div>
    </div>
  );
}
